### PR TITLE
Adding requirements.txt

### PR DESCRIPTION
**Pull request by zacharyjhumphrey**

### CODE REVIEW

**Comment by JALusk** [comment]
@zacharyjhumphrey Thanks for adding that. I'll test this out and let you know if there are any more changes that need to be made.

**Comment by JALusk** [comment]
I'm not familiar with the pyerfa package -- what functions does that provide?

**Comment by JALusk** [comment]
The formatting of the requirements.txt file also looks odd - I think this might be because of the different ways that Unix and Windows do line breaks and carriage returns. It looks like there's an option in Visual Studio to fix the problem:

https://stackoverflow.com/questions/3802406/configure-visual-studio-to-use-unix-line-endings

Once you make the changes, just push the branch to your github repository, and this pull request should update automatically.

Cheers,
Dr. Lusk

**Comment by zacharyjhumphrey** [comment]
Looks like it's a requirement for the astropy package: Here's a [link](https://docs.astropy.org/en/stable/install.html#requirements)

**Comment by zacharyjhumphrey** [comment]
@JALusk I just tried to fix the error in my most recent push. When you find the time, could you see if that fixed the issue?

**Comment by JALusk** [comment]
I ran your requirements.txt file through dos2unix to remove some non-printing characters that were still in there. I've attached the result to this comment, so you can replace the one in your git repository and then commit and push to github, which should fix the last issue.

[requirements.txt](https://github.com/JALusk/SuperBoL/files/7212485/requirements.txt)

**Pull request merged**
